import apps from './apps'
import charts from './charts'
import crm from './crm'
import dashboard from './dashboard'
import forms from './forms'
import hris from './hris'
import misc from './misc'
import pages from './pages'
import rme from './rme'
import satusehat from './satusehat'
import tables from './tables'
import transaction from './transaction'
import uiElements from './ui-elements'
import wms from './wms'

export default [...dashboard, ...rme, ...satusehat, ...transaction, ...wms, ...hris, ...crm, ...apps, ...pages, ...uiElements, ...forms, ...tables, ...charts, ...misc]
