import appsAndPages from './apps-and-pages'
import charts from './charts'
import crm from './crm'
import dashboard from './dashboard'
import finance from './finance'
import forms from './forms'
import hris from './hris'
import others from './others'
import rme from './rme'
import satusehat from './satusehat'
import setting from './setting'
import transaction from './transaction'
import uiElements from './ui-elements'
import wms from './wms'

export default [...dashboard, ...rme, ...satusehat, ...setting, ...transaction, ...wms, ...hris, ...crm, ...finance, ...appsAndPages, ...uiElements, ...forms, ...charts, ...others]
